### ISSUE TITLE
Example UI in README

### ISSUE THREAD

**Issue by aegershman** [pivotalservices/ignition#6]
I'm guessing this project is under such rapid development that taking UI screenshots would be outdated quickly, but nonetheless:

It would be nice if the README contained some examples of what this project offers. Even some rudimentary UI examples would be nice.

**Comment by ChristmasTaco** [comment]
Thanks for the request. As the readme is owned by the development team I will leave the decision to add these designs to that document to them.

For now, here is a current version of the design:

![ignition_home_v1](https://user-images.githubusercontent.com/12519848/38999793-d86fa2f6-43af-11e8-8398-ee00dc74a8d7.png)

**Comment by joefitzgerald** [comment]
@ChristmasTaco you are welcome to update the README!
